# Generated by Django 2.2.12 on 2022-10-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Time',
            fields=[
                ('id_client', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fio_client', models.CharField(max_length=255)),
                ('passport_number_client', models.SmallIntegerField(default=None)),
                ('date_of_birthday_client', models.DateField()),
                ('phone_number_client', models.IntegerField()),
                ('client_type', models.SmallIntegerField(choices=[(0, 'Постоянный'), (1, 'Временный'), (2, 'Одноразовый')])),
                ('link_photo1_client', models.ImageField(default=None, upload_to='client_img')),
                ('link_photo2_client', models.ImageField(default=None, upload_to='client_img')),
                ('link_photo3_client', models.ImageField(default=None, upload_to='client_img')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id_worker', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fio_worker', models.CharField(max_length=255)),
                ('passport_number_worker', models.SmallIntegerField(default=None)),
                ('date_of_birthday_worker', models.DateField()),
                ('snils', models.CharField(max_length=255)),
                ('adrress_worker', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('link_photo1_worker', models.ImageField(default=None, upload_to='client_img')),
                ('link_photo2_worker', models.ImageField(default=None, upload_to='client_img')),
                ('link_photo3_worker', models.ImageField(default=None, upload_to='client_img')),
                ('job_tittle', models.CharField(max_length=255)),
                ('security', models.BooleanField(default=False)),
                ('date_of_registration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Protect_points',
            fields=[
                ('id_point', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_point', models.CharField(max_length=255)),
                ('adress_point', models.CharField(max_length=255)),
                ('id_superviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Prohod_place',
            fields=[
                ('id_prohod', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('id_clietn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Client_Time')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id_error', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type_error', models.SmallIntegerField(choices=[(0, 'Ошибка распознования фото'), (1, 'Ошибка програмного обеспечения'), (2, 'ЧП')])),
                ('about_error', models.TextField()),
                ('date_error', models.DateField()),
                ('screen_error', models.ImageField(default=None, upload_to='error_img')),
                ('id_clietn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Client_Time')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Dostups',
            fields=[
                ('id_dostup', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dostup_start', models.DateField()),
                ('dostup_end', models.DateField()),
                ('id_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Protect_points')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Worker')),
            ],
        ),
    ]
