# Generated by Django 2.2.12 on 2022-10-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20221015_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostups',
            name='id_point',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='security.Protect_points'),
        ),
        migrations.AlterField(
            model_name='dostups',
            name='id_worker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='security.Worker'),
        ),
        migrations.AlterField(
            model_name='error',
            name='id_clietn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='security.Client_Time'),
        ),
        migrations.AlterField(
            model_name='error',
            name='id_worker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='security.Worker'),
        ),
        migrations.AlterField(
            model_name='prohod_place',
            name='id_clietn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='security.Client_Time'),
        ),
        migrations.AlterField(
            model_name='prohod_place',
            name='id_worker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='security.Worker'),
        ),
    ]
