# Generated by Django 4.1.2 on 2022-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_client_time_link_photo1_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_time',
            name='passport_number_client',
            field=models.CharField(max_length=255),
        ),
    ]
