# Generated by Django 4.1.2 on 2023-02-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_alter_client_time_phone_number_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_time',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], default=None),
            preserve_default=False,
        ),
    ]
