# Generated by Django 4.1.2 on 2023-04-06 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_client_time_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='id_clietn',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.client_time'),
        ),
        migrations.AlterField(
            model_name='error',
            name='id_worker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.worker'),
        ),
    ]
